matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd ./front
      script:
        - ./build.sh
      cache:
        directories:
        - "node_modules"
